components:
  schemas:
    Produto:
      type: object
      required:
        - nome
        - categoria
        - precoSugerido
      properties:
        id:
          type: number
          description: ID do produto, gerado automaticamente
        nome:
          type: string
          description: O nome do produto
        categoria:
          type: string
          description: A categoria do produto
        precoSugerido:
          type: number
          description: Preço sugerido para o produto
      example:
         id: 1
         nome: Café
         categoria: Alimentos
         precoSugerido: 15
    Error:
       type: object
       properties:
         error:
           type: string
paths:
  /produtos:
    get:
      summary: Obtém todos os produtos
      responses:
        200:
          description: Um array de produtos
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Produto'
        500:
          description: Erro no servidor ao tentar buscar os produtos
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Error'
    post:
      summary: Cria um novo produto
      requestBody:
        required: true
        content:
          application/json:
            schema:
                  $ref: '#/components/schemas/Produto'
      responses:
        201:
          description: O produto criado
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Produto'
        500:
          description: Erro no servidor ao tentar criar o produto
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Error'
    put:
      summary: Atualiza um produto pelo ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        204:
          description: O produto foi atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        404:
          description: O produto não foi encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Erro no servidor ao tentar atualizar o produto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /produtos/{id}:
    get:
      summary: Obtém um produto pelo ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: O ID do produto
      responses:
        200:
          description: O produto com o ID buscado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'
        404:
          description: O produto não foi encontrado
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Error'
        500:
          description: Erro no servidor ao tentar buscar o produto
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Error'
    delete:
      summary: Deleta um produto pelo ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: O ID do produto
      responses:
        201:
          description: O produto foi deletado com sucesso
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Produto'
        404:
          description: O produto não foi encontrado
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Error'
        500:
          description: Erro no servidor ao tentar deletar o produto
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Error'